//
// CooeyAPIClient
// AlmanacV3API.swift
//
// Generated by Eldhose Lomy
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class AlmanacV3API {
    /**

     - parameter userId: (path)  
     - parameter filterBy: (query)  (optional)
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 10)
     - parameter showActions: (query)  (optional, default to false)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getFacts(userId: String, filterBy: String? = nil, offset: Int? = nil, limit: Int? = nil, showActions: Bool? = nil, completion: @escaping ((_ data: PagedResultFactDTO?,_ error: Error?) -> Void)) {
        getFactsWithRequestBuilder(userId: userId, filterBy: filterBy, offset: offset, limit: limit, showActions: showActions).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v3/almanac/users/{userId}
     - examples: [{contentType=application/json, example={
  "result" : [ {
    "forUser" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "fullName" : "fullName",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    },
    "actorId" : "actorId",
    "forId" : "forId",
    "change" : {
      "reason" : "reason",
      "changeJson" : "changeJson",
      "propertyChanges" : [ {
        "propertyName" : "propertyName"
      }, {
        "propertyName" : "propertyName"
      } ],
      "entityType" : "APPOINTMENT",
      "name" : "name",
      "entityId" : "entityId",
      "id" : "id",
      "updatedOn" : 9,
      "createdOn" : 7
    },
    "entityId" : "entityId",
    "id" : "id",
    "changeId" : "changeId",
    "type" : "VITAL_ADDED",
    "actorUser" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "fullName" : "fullName",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    },
    "entity" : "{}",
    "timestamp" : 1
  }, {
    "forUser" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "fullName" : "fullName",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    },
    "actorId" : "actorId",
    "forId" : "forId",
    "change" : {
      "reason" : "reason",
      "changeJson" : "changeJson",
      "propertyChanges" : [ {
        "propertyName" : "propertyName"
      }, {
        "propertyName" : "propertyName"
      } ],
      "entityType" : "APPOINTMENT",
      "name" : "name",
      "entityId" : "entityId",
      "id" : "id",
      "updatedOn" : 9,
      "createdOn" : 7
    },
    "entityId" : "entityId",
    "id" : "id",
    "changeId" : "changeId",
    "type" : "VITAL_ADDED",
    "actorUser" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "fullName" : "fullName",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    },
    "entity" : "{}",
    "timestamp" : 1
  } ],
  "offset" : 6,
  "totalPages" : 5,
  "totalCount" : 0
}}]
     
     - parameter userId: (path)  
     - parameter filterBy: (query)  (optional)
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 10)
     - parameter showActions: (query)  (optional, default to false)

     - returns: RequestBuilder<PagedResultFactDTO> 
     */
    open class func getFactsWithRequestBuilder(userId: String, filterBy: String? = nil, offset: Int? = nil, limit: Int? = nil, showActions: Bool? = nil) -> RequestBuilder<PagedResultFactDTO> {
        var path = "/ehealth/v3/almanac/users/{userId}"
        let userIdPreEscape = "\(userId)"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "filterBy": filterBy, 
            "offset": offset?.encodeToJSON(), 
            "limit": limit?.encodeToJSON(), 
            "show_actions": showActions
        ])

        let requestBuilder: RequestBuilder<PagedResultFactDTO>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
