//
// CooeyAPIClient
// AlmanacAPI.swift
//
// Generated by Eldhose Lomy
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class AlmanacAPI {
    /**

     - parameter userId: (path)  
     - parameter filterBy: (query)  (optional)
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 10)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getFacts(userId: String, filterBy: String? = nil, offset: Int? = nil, limit: Int? = nil, completion: @escaping ((_ data: PagedResultFactResponse?,_ error: Error?) -> Void)) {
        getFactsWithRequestBuilder(userId: userId, filterBy: filterBy, offset: offset, limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/almanac/users/{userId}
     - examples: [{contentType=application/json, example={
  "result" : [ {
    "actorId" : "actorId",
    "forName" : "forName",
    "forId" : "forId",
    "entityId" : "entityId",
    "actorName" : "actorName",
    "id" : "id",
    "changeId" : "changeId",
    "type" : "VITAL_ADDED",
    "entity" : "{}",
    "timestamp" : 1
  }, {
    "actorId" : "actorId",
    "forName" : "forName",
    "forId" : "forId",
    "entityId" : "entityId",
    "actorName" : "actorName",
    "id" : "id",
    "changeId" : "changeId",
    "type" : "VITAL_ADDED",
    "entity" : "{}",
    "timestamp" : 1
  } ],
  "offset" : 6,
  "totalCount" : 0
}}]
     
     - parameter userId: (path)  
     - parameter filterBy: (query)  (optional)
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 10)

     - returns: RequestBuilder<PagedResultFactResponse> 
     */
    open class func getFactsWithRequestBuilder(userId: String, filterBy: String? = nil, offset: Int? = nil, limit: Int? = nil) -> RequestBuilder<PagedResultFactResponse> {
        var path = "/ehealth/v2/almanac/users/{userId}"
        let userIdPreEscape = "\(userId)"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "filterBy": filterBy, 
            "offset": offset?.encodeToJSON(), 
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<PagedResultFactResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
