//
// CooeyAPIClient
// ChannelsAPI.swift
//
// Generated by Eldhose Lomy
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ChannelsAPI {
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createChannel(body: Channel? = nil, completion: @escaping ((_ data: Channel?,_ error: Error?) -> Void)) {
        createChannelWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /ehealth/v2/channels
     - examples: [{contentType=application/json, example={
  "sourceId" : "sourceId",
  "archived" : false,
  "tenantId" : "tenantId",
  "externalId" : "externalId",
  "active" : false,
  "updatedOn" : 6,
  "id" : "id",
  "source" : "source",
  "applicationId" : "applicationId",
  "type" : "NOTIFICATION",
  "createdOn" : 0,
  "userId" : "userId"
}}]
     
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Channel> 
     */
    open class func createChannelWithRequestBuilder(body: Channel? = nil) -> RequestBuilder<Channel> {
        let path = "/ehealth/v2/channels"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Channel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**

     - parameter userId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getChannelsForUser(userId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [Channel]?,_ error: Error?) -> Void)) {
        getChannelsForUserWithRequestBuilder(userId: userId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/channels/{userId}
     - examples: [{contentType=application/json, example=[ {
  "sourceId" : "sourceId",
  "archived" : false,
  "tenantId" : "tenantId",
  "externalId" : "externalId",
  "active" : false,
  "updatedOn" : 6,
  "id" : "id",
  "source" : "source",
  "applicationId" : "applicationId",
  "type" : "NOTIFICATION",
  "createdOn" : 0,
  "userId" : "userId"
}, {
  "sourceId" : "sourceId",
  "archived" : false,
  "tenantId" : "tenantId",
  "externalId" : "externalId",
  "active" : false,
  "updatedOn" : 6,
  "id" : "id",
  "source" : "source",
  "applicationId" : "applicationId",
  "type" : "NOTIFICATION",
  "createdOn" : 0,
  "userId" : "userId"
} ]}]
     
     - parameter userId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[Channel]> 
     */
    open class func getChannelsForUserWithRequestBuilder(userId: String, xAuthToken: String? = nil) -> RequestBuilder<[Channel]> {
        var path = "/ehealth/v2/channels/{userId}"
        let userIdPreEscape = "\(userId)"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "x-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Channel]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter fcmToken: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func logOutUser(fcmToken: String, xAuthToken: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        logOutUserWithRequestBuilder(fcmToken: fcmToken, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /ehealth/v2/channels/{fcmToken}
     
     - parameter fcmToken: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func logOutUserWithRequestBuilder(fcmToken: String, xAuthToken: String? = nil) -> RequestBuilder<Void> {
        var path = "/ehealth/v2/channels/{fcmToken}"
        let fcmTokenPreEscape = "\(fcmToken)"
        let fcmTokenPostEscape = fcmTokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{fcmToken}", with: fcmTokenPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "x-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
