//
// CooeyAPIClient
// CommunicationsAPI.swift
//
// Generated by Eldhose Lomy
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class CommunicationsAPI {
    /**

     - parameter userId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCommunicationContactDetails(userId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: ContactDetailsResponse?,_ error: Error?) -> Void)) {
        getCommunicationContactDetailsWithRequestBuilder(userId: userId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/communications/contact/user/{userId}
     - examples: [{contentType=application/json, example={
  "caretakers" : [ {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  }, {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  } ],
  "patient" : {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  },
  "guardians" : [ {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  }, {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  } ]
}}]
     
     - parameter userId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<ContactDetailsResponse> 
     */
    open class func getCommunicationContactDetailsWithRequestBuilder(userId: String, xAuthToken: String? = nil) -> RequestBuilder<ContactDetailsResponse> {
        var path = "/ehealth/v2/communications/contact/user/{userId}"
        let userIdPreEscape = "\(userId)"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ContactDetailsResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter guardianId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getContactDetailsForGuardian(guardianId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [GuardianContactDetailResponse]?,_ error: Error?) -> Void)) {
        getContactDetailsForGuardianWithRequestBuilder(guardianId: guardianId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/communications/contact/guardian/{guardianId}
     - examples: [{contentType=application/json, example=[ {
  "caretakers" : [ {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  }, {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  } ],
  "patient" : {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  }
}, {
  "caretakers" : [ {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  }, {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  } ],
  "patient" : {
    "unreadMessageCount" : 6,
    "chatSessionId" : "chatSessionId",
    "recentMessageOn" : 0,
    "user" : {
      "country" : "country",
      "zipCode" : "zipCode",
      "occupation" : "occupation",
      "education" : "education",
      "groupId" : "groupId",
      "type" : "type",
      "shiftTimings" : "shiftTimings",
      "internalId" : "internalId",
      "bloodGroup" : "bloodGroup",
      "password" : "password",
      "id" : "id",
      "profilePhotoId" : "profilePhotoId",
      "governmentId" : "governmentId",
      "height" : {
        "unit" : "unit",
        "value" : 2.027123
      },
      "maratialstatus" : "maratialstatus",
      "emergencyContact" : "emergencyContact",
      "active" : false,
      "weight" : {
        "unit" : "unit",
        "value" : 3.6160767
      },
      "timeZone" : "timeZone",
      "passwordResetEnabled" : false,
      "updatedOn" : 6,
      "profilePhotoURL" : "profilePhotoURL",
      "firstName" : "firstName",
      "authenticationProvider" : "COOEY",
      "userSettings" : {
        "featureList" : {
          "key" : true
        },
        "vitalLimitNotificationEnabled" : false,
        "defaultNotificationMode" : "PUSH_NOTIFICATION",
        "vitalNotificationEnabled" : false,
        "eventNotificationEnabled" : false,
        "vitalLimits" : [ {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        }, {
          "higherLimit" : 5.637377,
          "lowerLimit" : 5.962134,
          "limitType" : "limitType"
        } ],
        "notificationEnabled" : false
      },
      "hipSize" : {
        "unit" : "unit",
        "value" : 4.145608
      },
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status",
      "lastName" : "lastName",
      "userStatus" : 7,
      "gender" : "gender",
      "authToken" : "authToken",
      "careTaker" : "careTaker",
      "createdOn" : 0,
      "authId" : "authId",
      "encryptedPassword" : "encryptedPassword",
      "archived" : false,
      "icdCodes" : [ "icdCodes", "icdCodes" ],
      "countryCode" : "countryCode",
      "skill" : "skill",
      "alarmId" : "alarmId",
      "currency" : "currency",
      "insuranceInformation" : {
        "primaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsuranceDetails" : {
          "authorizationNumber" : "authorizationNumber",
          "carrierName" : "carrierName",
          "insuranceId" : "insuranceId"
        },
        "secondaryInsured" : false
      },
      "allergires" : [ {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      }, {
        "symptoms" : [ "symptoms", "symptoms" ],
        "level" : "LOW",
        "name" : "name"
      } ],
      "hourlyPrice" : 1.2315135,
      "email" : "email",
      "shiftId" : "shiftId",
      "address" : {
        "zipCode" : "zipCode",
        "country" : "country",
        "lng" : "lng",
        "pin" : "pin",
        "city" : "city",
        "location" : "location",
        "state" : "state",
        "line2" : "line2",
        "line1" : "line1",
        "lat" : "lat"
      },
      "mobile" : "mobile",
      "externalId" : "externalId",
      "dateOfBirth" : 1,
      "room" : "room",
      "additionalInfoList" : [ {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      }, {
        "template" : "{}",
        "archived" : false,
        "contextGraphEnabled" : false,
        "tenantId" : "tenantId",
        "externalId" : "externalId",
        "active" : false,
        "updatedOn" : 1,
        "applicationId" : "applicationId",
        "title" : "title",
        "type" : "type",
        "createdOn" : 7,
        "mandatory" : false
      } ],
      "profileTags" : [ "profileTags", "profileTags" ],
      "waistSize" : {
        "unit" : "unit",
        "value" : 7.386282
      },
      "tenantId" : "tenantId",
      "pulse" : "pulse",
      "category" : "category",
      "publicId" : 2,
      "age" : 9,
      "username" : "username"
    }
  }
} ]}]
     
     - parameter guardianId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[GuardianContactDetailResponse]> 
     */
    open class func getContactDetailsForGuardianWithRequestBuilder(guardianId: String, xAuthToken: String? = nil) -> RequestBuilder<[GuardianContactDetailResponse]> {
        var path = "/ehealth/v2/communications/contact/guardian/{guardianId}"
        let guardianIdPreEscape = "\(guardianId)"
        let guardianIdPostEscape = guardianIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{guardianId}", with: guardianIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[GuardianContactDetailResponse]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
