//
// CooeyAPIClient
// DeviceEventsAPI.swift
//
// Generated by Eldhose Lomy
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class DeviceEventsAPI {
    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getEmergencyAlerts(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [EmergencyAlertMessage]?,_ error: Error?) -> Void)) {
        getEmergencyAlertsWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/alert/emergency
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[EmergencyAlertMessage]> 
     */
    open class func getEmergencyAlertsWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[EmergencyAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/alert/emergency"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[EmergencyAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getFullBatteryReadings(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [BatteryStatusAlertMessage]?,_ error: Error?) -> Void)) {
        getFullBatteryReadingsWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/battery/fullcharge
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "batteryHealth" : "batteryHealth",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "batteryHealth" : "batteryHealth",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[BatteryStatusAlertMessage]> 
     */
    open class func getFullBatteryReadingsWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[BatteryStatusAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/battery/fullcharge"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[BatteryStatusAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getGeoFenceAlerts(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [GeofencingAlertMessage]?,_ error: Error?) -> Void)) {
        getGeoFenceAlertsWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/alert/geofence
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "geoFenceOutside" : "geoFenceOutside",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "geoFenceNumber" : "geoFenceNumber",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "geoFenceOutside" : "geoFenceOutside",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "geoFenceNumber" : "geoFenceNumber",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[GeofencingAlertMessage]> 
     */
    open class func getGeoFenceAlertsWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[GeofencingAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/alert/geofence"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[GeofencingAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getHazardousAlerts(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [HazardousMovementAlertMessage]?,_ error: Error?) -> Void)) {
        getHazardousAlertsWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/alert/hazard
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[HazardousMovementAlertMessage]> 
     */
    open class func getHazardousAlertsWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[HazardousMovementAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/alert/hazard"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[HazardousMovementAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getLowBatteryReadings(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [BatteryStatusAlertMessage]?,_ error: Error?) -> Void)) {
        getLowBatteryReadingsWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/battery/lowcharge
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "batteryHealth" : "batteryHealth",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "batteryHealth" : "batteryHealth",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[BatteryStatusAlertMessage]> 
     */
    open class func getLowBatteryReadingsWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[BatteryStatusAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/battery/lowcharge"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[BatteryStatusAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getLowMovementAlerts(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [LowMovementAlertMessage]?,_ error: Error?) -> Void)) {
        getLowMovementAlertsWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/alert/lowmovement
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "lowMovementValue" : "lowMovementValue",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "lowMovementValue" : "lowMovementValue",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[LowMovementAlertMessage]> 
     */
    open class func getLowMovementAlertsWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[LowMovementAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/alert/lowmovement"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[LowMovementAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getPowerOffStatus(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [DevicePowerAlertMessage]?,_ error: Error?) -> Void)) {
        getPowerOffStatusWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/power/off
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[DevicePowerAlertMessage]> 
     */
    open class func getPowerOffStatusWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[DevicePowerAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/power/off"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[DevicePowerAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getPowerOnStatus(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [DevicePowerAlertMessage]?,_ error: Error?) -> Void)) {
        getPowerOnStatusWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/power/on
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[DevicePowerAlertMessage]> 
     */
    open class func getPowerOnStatusWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[DevicePowerAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/power/on"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[DevicePowerAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getShockAlerts(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [ShockAlertMessage]?,_ error: Error?) -> Void)) {
        getShockAlertsWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/alert/shock
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "shockValue" : "shockValue",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "shockValue" : "shockValue",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[ShockAlertMessage]> 
     */
    open class func getShockAlertsWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[ShockAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/alert/shock"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[ShockAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getTemperatureAlerts(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [TemperatureAlertMessage]?,_ error: Error?) -> Void)) {
        getTemperatureAlertsWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/alert/temperature
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "steps" : "steps",
  "command" : "AUTHORIZE",
  "temperatureAlertValue" : "temperatureAlertValue",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "steps" : "steps",
  "command" : "AUTHORIZE",
  "temperatureAlertValue" : "temperatureAlertValue",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[TemperatureAlertMessage]> 
     */
    open class func getTemperatureAlertsWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[TemperatureAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/alert/temperature"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[TemperatureAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getTrackingAlerts(patientId: String, xAuthToken: String? = nil, completion: @escaping ((_ data: [TrackingAlertMessage]?,_ error: Error?) -> Void)) {
        getTrackingAlertsWithRequestBuilder(patientId: patientId, xAuthToken: xAuthToken).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/devices/{patientId}/alert/tracking
     - examples: [{contentType=application/json, example=[ {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "steps" : "steps",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
}, {
  "altitude" : "altitude",
  "perpendicularUncertainity" : "perpendicularUncertainity",
  "heading" : "heading",
  "latitude" : 1.4658129805029452,
  "altitudeUncertainity" : "altitudeUncertainity",
  "fullMessage" : "fullMessage",
  "gpsSpeed" : "gpsSpeed",
  "commandExtension" : "NONE",
  "commandId" : "AUTHORIZE",
  "deviceId" : "deviceId",
  "createdOn" : "2000-01-23T04:56:07.000+00:00",
  "steps" : "steps",
  "command" : "AUTHORIZE",
  "payloadSize" : 0,
  "batteryStatus" : "batteryStatus",
  "horizontalUncertainityAngle" : "horizontalUncertainityAngle",
  "horizontalUncertainity" : "horizontalUncertainity",
  "temperature" : "temperature",
  "assistedGPS" : "assistedGPS",
  "id" : "id",
  "timestamp" : 6,
  "longitude" : 5.962133916683182
} ]}]
     
     - parameter patientId: (path)  
     - parameter xAuthToken: (header)  (optional)

     - returns: RequestBuilder<[TrackingAlertMessage]> 
     */
    open class func getTrackingAlertsWithRequestBuilder(patientId: String, xAuthToken: String? = nil) -> RequestBuilder<[TrackingAlertMessage]> {
        var path = "/ehealth/v2/devices/{patientId}/alert/tracking"
        let patientIdPreEscape = "\(patientId)"
        let patientIdPostEscape = patientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{patientId}", with: patientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[TrackingAlertMessage]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
