//
// CooeyAPIClient
// Icd10API.swift
//
// Generated by Eldhose Lomy
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class Icd10API {
    /**

     - parameter categoryNo: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func diagnosisCodeByCategoryNo(categoryNo: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        diagnosisCodeByCategoryNoWithRequestBuilder(categoryNo: categoryNo).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - GET /ehealth/v2/icd-10/category/numbers/{categoryNo}
     
     - parameter categoryNo: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func diagnosisCodeByCategoryNoWithRequestBuilder(categoryNo: String) -> RequestBuilder<Void> {
        var path = "/ehealth/v2/icd-10/category/numbers/{categoryNo}"
        let categoryNoPreEscape = "\(categoryNo)"
        let categoryNoPostEscape = categoryNoPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{categoryNo}", with: categoryNoPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter codeId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func diagnosisCodeByCode(codeId: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        diagnosisCodeByCodeWithRequestBuilder(codeId: codeId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - GET /ehealth/v2/icd-10/codes/{codeId}
     
     - parameter codeId: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func diagnosisCodeByCodeWithRequestBuilder(codeId: String) -> RequestBuilder<Void> {
        var path = "/ehealth/v2/icd-10/codes/{codeId}"
        let codeIdPreEscape = "\(codeId)"
        let codeIdPostEscape = codeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{codeId}", with: codeIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter code: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter offset: (query)  (optional)
     - parameter limit: (query)  (optional, default to 10)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func search(code: String? = nil, _description: String? = nil, offset: Int64? = nil, limit: Int? = nil, completion: @escaping ((_ data: PagedResultDiagnosisCodeResponseDTO?,_ error: Error?) -> Void)) {
        searchWithRequestBuilder(code: code, _description: _description, offset: offset, limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /ehealth/v2/icd-10/codes/search
     - examples: [{contentType=application/json, example={
  "result" : [ {
    "description" : "description",
    "id" : "id",
    "category" : "category"
  }, {
    "description" : "description",
    "id" : "id",
    "category" : "category"
  } ],
  "offset" : 6,
  "totalCount" : 0
}}]
     
     - parameter code: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter offset: (query)  (optional)
     - parameter limit: (query)  (optional, default to 10)

     - returns: RequestBuilder<PagedResultDiagnosisCodeResponseDTO> 
     */
    open class func searchWithRequestBuilder(code: String? = nil, _description: String? = nil, offset: Int64? = nil, limit: Int? = nil) -> RequestBuilder<PagedResultDiagnosisCodeResponseDTO> {
        let path = "/ehealth/v2/icd-10/codes/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "code": code, 
            "description": _description, 
            "offset": offset?.encodeToJSON(), 
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<PagedResultDiagnosisCodeResponseDTO>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
