//
// CooeyAPIClient
// VisionAPI.swift
//
// Generated by Eldhose Lomy
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class VisionAPI {
    /**

     - parameter xAuthToken: (header)  (optional)
     - parameter VITAL_TYPE: (query)  (optional)
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func performVisualAnalysis(xAuthToken: String? = nil, VITAL_TYPE: String? = nil, body: InputStream? = nil, completion: @escaping ((_ data: VisionAnalysisResponseDeviceVisionAnalysis?,_ error: Error?) -> Void)) {
        performVisualAnalysisWithRequestBuilder(xAuthToken: xAuthToken, VITAL_TYPE: VITAL_TYPE, body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /ehealth/v2/vision
     - examples: [{contentType=application/json, example={
  "type" : "DEVICE",
  "analysis" : {
    "identifiedValues" : [ {
      "boundingBox" : {
        "top" : 6.027456183070403,
        "left" : 0.8008281904610115,
        "width" : 1.4658129805029452,
        "height" : 5.962133916683182
      },
      "value" : "value",
      "key" : "key"
    }, {
      "boundingBox" : {
        "top" : 6.027456183070403,
        "left" : 0.8008281904610115,
        "width" : 1.4658129805029452,
        "height" : 5.962133916683182
      },
      "value" : "value",
      "key" : "key"
    } ],
    "unidentifiedValues" : [ {
      "boundingBox" : {
        "top" : 6.027456183070403,
        "left" : 0.8008281904610115,
        "width" : 1.4658129805029452,
        "height" : 5.962133916683182
      },
      "value" : "value"
    }, {
      "boundingBox" : {
        "top" : 6.027456183070403,
        "left" : 0.8008281904610115,
        "width" : 1.4658129805029452,
        "height" : 5.962133916683182
      },
      "value" : "value"
    } ],
    "device" : {
      "mobileNumber" : "mobileNumber",
      "externalId" : "externalId",
      "active" : false,
      "updatedOn" : 6,
      "type" : "type",
      "createdOn" : 0,
      "userId" : "userId",
      "deviceId" : "deviceId",
      "archived" : false,
      "tenantId" : "tenantId",
      "name" : "name",
      "id" : "id",
      "applicationId" : "applicationId",
      "parameters" : "parameters",
      "status" : "status"
    }
  }
}}]
     
     - parameter xAuthToken: (header)  (optional)
     - parameter VITAL_TYPE: (query)  (optional)
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<VisionAnalysisResponseDeviceVisionAnalysis> 
     */
    open class func performVisualAnalysisWithRequestBuilder(xAuthToken: String? = nil, VITAL_TYPE: String? = nil, body: InputStream? = nil) -> RequestBuilder<VisionAnalysisResponseDeviceVisionAnalysis> {
        let path = "/ehealth/v2/vision"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "VITAL_TYPE": VITAL_TYPE
        ])
        let nillableHeaders: [String: Any?] = [
            "X-Auth-Token": xAuthToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<VisionAnalysisResponseDeviceVisionAnalysis>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }

}
