//
// CooeyAPIClient
// ActionGroupsResponse.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ActionGroupsResponse: Codable {

    public var totalCount: Int64?
    public var offset: Int64?
    public var result: [ActionGroup]?

    public init() {
    }

    public init(totalCount: Int64?, offset: Int64?, result: [ActionGroup]?) {
        self.totalCount = totalCount
        self.offset = offset
        self.result = result
    }


}

