//
// CooeyAPIClient
// ActionItemResponse.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ActionItemResponse: Codable {

    public var grouppedActionResponse: [GrouppedActionResponse]?
    public var ungrouppedActionItems: [ActionItem]?
    public var timeTrackabel: Bool?

    public init() {
    }

    public init(grouppedActionResponse: [GrouppedActionResponse]?, ungrouppedActionItems: [ActionItem]?, timeTrackabel: Bool?) {
        self.grouppedActionResponse = grouppedActionResponse
        self.ungrouppedActionItems = ungrouppedActionItems
        self.timeTrackabel = timeTrackabel
    }


}

