//
// CooeyAPIClient
// AdhocTasks.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct AdhocTasks: Codable {

    public var name: String?

    public init() {
    }

    public init(name: String?) {
        self.name = name
    }


}

