//
// CooeyAPIClient
// Agencies.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Agencies: Codable {

    public var name: String?

    public init() {
    }

    public init(name: String?) {
        self.name = name
    }


}

