//
// CooeyAPIClient
// APIHook.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct APIHook: Codable {

    public var id: String?
    public var url: String?
    public var events: [String]?

    public init() {
    }

    public init(id: String?, url: String?, events: [String]?) {
        self.id = id
        self.url = url
        self.events = events
    }


}

