//
// CooeyAPIClient
// AppointmentPOSTRequest.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct AppointmentPOSTRequest: Codable {

    public enum RequestedByAccountType: String, Codable { 
        case patient = "PATIENT"
        case tenant = "TENANT"
        case guardian = "GUARDIAN"
        case admin = "ADMIN"
        case careTaker = "CARE_TAKER"
        case user = "USER"
        case groupAdmin = "GROUP_ADMIN"
    }
    public var title: String?
    public var _description: String?
    public var schedule: Schedule?
    public var createdBy: String?
    public var attenderId: String?
    public var attendeeId: String?
    public var attenderName: String?
    public var attendeeName: String?
    public var requestedBy: String?
    public var lastUpdatedBy: String?
    public var offerings: [Product]?
    public var serviceIds: [String]?
    public var blueprints: [InterventionBlueprint]?
    public var requestedByAccountType: RequestedByAccountType?
    public var tenantId: String?

    public init() {
    }

    public init(title: String?, _description: String?, schedule: Schedule?, createdBy: String?, attenderId: String?, attendeeId: String?, attenderName: String?, attendeeName: String?, requestedBy: String?, lastUpdatedBy: String?, offerings: [Product]?, serviceIds: [String]?, blueprints: [InterventionBlueprint]?, requestedByAccountType: RequestedByAccountType?, tenantId: String?) {
        self.title = title
        self._description = _description
        self.schedule = schedule
        self.createdBy = createdBy
        self.attenderId = attenderId
        self.attendeeId = attendeeId
        self.attenderName = attenderName
        self.attendeeName = attendeeName
        self.requestedBy = requestedBy
        self.lastUpdatedBy = lastUpdatedBy
        self.offerings = offerings
        self.serviceIds = serviceIds
        self.blueprints = blueprints
        self.requestedByAccountType = requestedByAccountType
        self.tenantId = tenantId
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case _description = "description"
        case schedule
        case createdBy
        case attenderId
        case attendeeId
        case attenderName
        case attendeeName
        case requestedBy
        case lastUpdatedBy
        case offerings
        case serviceIds
        case blueprints
        case requestedByAccountType
        case tenantId
    }


}

