//
// CooeyAPIClient
// AppointmentConfigDTO.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct AppointmentConfigDTO: Codable {

    public var patientEnabled: Bool?
    public var sendSMS: Bool?
    public var notifyGuardian: Bool?
    public var sendEmail: Bool?
    public var enableGuardian: Bool?
    public var version: String?

    public init() {
    }

    public init(patientEnabled: Bool?, sendSMS: Bool?, notifyGuardian: Bool?, sendEmail: Bool?, enableGuardian: Bool?, version: String?) {
        self.patientEnabled = patientEnabled
        self.sendSMS = sendSMS
        self.notifyGuardian = notifyGuardian
        self.sendEmail = sendEmail
        self.enableGuardian = enableGuardian
        self.version = version
    }


}

