//
// CooeyAPIClient
// BlobStorageDocument.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct BlobStorageDocument: Codable {

    public enum ReferralFormType: String, Codable { 
        case consent = "CONSENT"
        case advancedBeneficiaryConsent = "ADVANCED_BENEFICIARY_CONSENT"
        case physicianOrder = "PHYSICIAN_ORDER"
        case preAuthorization = "PRE_AUTHORIZATION"
        case telephoneOrder = "TELEPHONE_ORDER"
        case other = "OTHER"
    }
    public var id: String?
    public var name: String?
    public var _extension: String?
    public var referralFormType: ReferralFormType?

    public init() {
    }

    public init(id: String?, name: String?, _extension: String?, referralFormType: ReferralFormType) {
        self.id = id
        self.name = name
        self._extension = _extension
        self.referralFormType = referralFormType
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case _extension = "extension"
        case referralFormType
    }


}

