//
// CooeyAPIClient
// BoundingBox.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct BoundingBox: Codable {

    public var _left: Double?
    public var top: Double?
    public var width: Double?
    public var height: Double?

    public init() {
    }

    public init(_left: Double?, top: Double?, width: Double?, height: Double?) {
        self._left = _left
        self.top = top
        self.width = width
        self.height = height
    }

    public enum CodingKeys: String, CodingKey { 
        case _left = "left"
        case top
        case width
        case height
    }


}

