//
// CooeyAPIClient
// CareplanProgressIndicator.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct CareplanProgressIndicator: Codable {

    public var progressIndicator: Double?
    public var careplanId: String?
    public var message: String?
    public var patientId: String?
    public var otherCareplanNames: [String]?

    public init() {
    }

    public init(progressIndicator: Double?, careplanId: String?, message: String?, patientId: String?, otherCareplanNames: [String]?) {
        self.progressIndicator = progressIndicator
        self.careplanId = careplanId
        self.message = message
        self.patientId = patientId
        self.otherCareplanNames = otherCareplanNames
    }


}

