//
// CooeyAPIClient
// Channel.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Channel: Codable {

    public enum ModelType: String, Codable { 
        case notification = "NOTIFICATION"
        case email = "EMAIL"
        case call = "CALL"
        case sms = "SMS"
        case voip = "VOIP"
    }
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var id: String?
    public var sourceId: String?
    public var userId: String?
    public var type: ModelType?
    public var source: String?
    public var deviceId: String?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, id: String?, sourceId: String?, userId: String?, type: ModelType?, source: String?, deviceId: String?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.id = id
        self.sourceId = sourceId
        self.userId = userId
        self.type = type
        self.source = source
        self.deviceId = deviceId
    }


}

