//
// CooeyAPIClient
// ChangePasswordRequest.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ChangePasswordRequest: Codable {

    public var email: String?
    public var oldPwd: String?
    public var newPwd: String?
    public var userId: String?
    public var type: String?

    public init() {
    }

    public init(email: String?, oldPwd: String?, newPwd: String?, userId: String?, type: String?) {
        self.email = email
        self.oldPwd = oldPwd
        self.newPwd = newPwd
        self.userId = userId
        self.type = type
    }


}

