//
// CooeyAPIClient
// ChatSessionResponse.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ChatSessionResponse: Codable {

    public enum ModelType: String, Codable { 
        case individual = "INDIVIDUAL"
        case group = "GROUP"
    }
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var id: String?
    public var ownerId: String?
    public var name: String?
    public var contextType: String?
    public var contextId: String?
    public var recentMessageOn: Int64?
    public var type: ModelType?
    public var chatParticipations: [ChatParticipationResponse]?
    public var unreadMessageCount: Int64?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, id: String?, ownerId: String?, name: String?, contextType: String?, contextId: String?, recentMessageOn: Int64?, type: ModelType?, chatParticipations: [ChatParticipationResponse]?, unreadMessageCount: Int64?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.id = id
        self.ownerId = ownerId
        self.name = name
        self.contextType = contextType
        self.contextId = contextId
        self.recentMessageOn = recentMessageOn
        self.type = type
        self.chatParticipations = chatParticipations
        self.unreadMessageCount = unreadMessageCount
    }


}

