//
// CooeyAPIClient
// ChatMessage.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ChatMessage: Codable {

    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var id: String?
    public var content: String?
    public var type: String?
    public var fromUserId: String?
    public var sessionId: String?
    public var sentOn: Int64?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, id: String?, content: String?, type: String?, fromUserId: String?, sessionId: String?, sentOn: Int64?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.id = id
        self.content = content
        self.type = type
        self.fromUserId = fromUserId
        self.sessionId = sessionId
        self.sentOn = sentOn
    }


}

