//
// CooeyAPIClient
// Code.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Code: Codable {

    public var id: String?
    public var _description: String?
    public var billRate: Int?

    public init() {
    }

    public init(id: String?, _description: String?, billRate: Int?) {
        self.id = id
        self._description = _description
        self.billRate = billRate
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case _description = "description"
        case billRate
    }


}

