//
// CooeyAPIClient
// ConsentFilesRequestDTO.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ConsentFilesRequestDTO: Codable {

    public var consentFiles: [String]?
    public var reason: String?
    public var assignerId: String?

    public init() {
    }

    public init(consentFiles: [String], reason: String?, assignerId: String?) {
        self.consentFiles = consentFiles
        self.reason = reason
        self.assignerId = assignerId
    }


}

