//
// CooeyAPIClient
// ContactDetailsResponse.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ContactDetailsResponse: Codable {

    public var patient: ContactDetails?
    public var guardians: [ContactDetails]?
    public var caretakers: [ContactDetails]?

    public init() {
    }

    public init(patient: ContactDetails?, guardians: [ContactDetails]?, caretakers: [ContactDetails]?) {
        self.patient = patient
        self.guardians = guardians
        self.caretakers = caretakers
    }


}

