//
// CooeyAPIClient
// ContactDetails.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ContactDetails: Codable {

    public var chatSessionId: String?
    public var user: User?
    public var recentMessageOn: Int64?
    public var unreadMessageCount: Int64?

    public init() {
    }

    public init(chatSessionId: String?, user: User?, recentMessageOn: Int64?, unreadMessageCount: Int64?) {
        self.chatSessionId = chatSessionId
        self.user = user
        self.recentMessageOn = recentMessageOn
        self.unreadMessageCount = unreadMessageCount
    }


}

