//
// CooeyAPIClient
// CreateUserRequest.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct CreateUserRequest: Codable {

    public enum AuthenticationProvider: String, Codable { 
        case cooey = "COOEY"
        case facebook = "FACEBOOK"
        case google = "GOOGLE"
        case phone = "PHONE"
    }
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var id: String?
    public var firstName: String?
    public var lastName: String?
    public var dateOfBirth: Int64?
    public var email: String?
    public var username: String?
    public var password: String?
    public var authenticationProvider: AuthenticationProvider?
    public var country: String?
    public var mobile: String?
    public var gender: String?
    public var authId: String?
    public var authToken: String?
    public var userSettings: UserSettings?
    public var publicId: Int64?
    public var groupId: String?
    public var type: String?
    public var skill: String?
    public var icdCodes: [String]?
    public var additionalInfoList: [FieldComponent]?
    public var userStatus: Int?
    public var careTaker: String?
    public var alarmId: String?
    public var allergires: [Allergy]?
    public var room: String?
    public var governmentId: String?
    public var internalId: String?
    public var status: String?
    public var age: Int?
    public var weight: Weight?
    public var pulse: String?
    public var height: Height?
    public var hipSize: HipSize?
    public var waistSize: WaistSize?
    public var category: String?
    public var occupation: String?
    public var education: String?
    public var maratialstatus: String?
    public var parameters: String?
    public var bloodGroup: String?
    public var profilePhotoId: String?
    public var profilePhotoURL: String?
    public var emergencyContact: String?
    public var shiftId: String?
    public var shiftTimings: String?
    public var timeZone: String?
    public var hourlyPrice: Float?
    public var currency: String?
    public var profileTags: [String]?
    public var zipCode: String?
    public var encryptedPassword: String?
    public var countryCode: String?
    public var insuranceInformation: EpisodeInsuranceInformation?
    public var requestId: String?
    public var partnerId: String?
    public var fullName: String?
    public var address: Address?
    public var passwordResetEnabled: Bool?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, id: String?, firstName: String?, lastName: String?, dateOfBirth: Int64?, email: String?, username: String?, password: String?, authenticationProvider: AuthenticationProvider?, country: String?, mobile: String?, gender: String?, authId: String?, authToken: String?, userSettings: UserSettings?, publicId: Int64?, groupId: String?, type: String?, skill: String?, icdCodes: [String]?, additionalInfoList: [FieldComponent]?, userStatus: Int?, careTaker: String?, alarmId: String?, allergires: [Allergy]?, room: String?, governmentId: String?, internalId: String?, status: String?, age: Int?, weight: Weight?, pulse: String?, height: Height?, hipSize: HipSize?, waistSize: WaistSize?, category: String?, occupation: String?, education: String?, maratialstatus: String?, parameters: String?, bloodGroup: String?, profilePhotoId: String?, profilePhotoURL: String?, emergencyContact: String?, shiftId: String?, shiftTimings: String?, timeZone: String?, hourlyPrice: Float?, currency: String?, profileTags: [String]?, zipCode: String?, encryptedPassword: String?, countryCode: String?, insuranceInformation: EpisodeInsuranceInformation?, requestId: String?, partnerId: String?, fullName: String?, address: Address?, passwordResetEnabled: Bool?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.id = id
        self.firstName = firstName
        self.lastName = lastName
        self.dateOfBirth = dateOfBirth
        self.email = email
        self.username = username
        self.password = password
        self.authenticationProvider = authenticationProvider
        self.country = country
        self.mobile = mobile
        self.gender = gender
        self.authId = authId
        self.authToken = authToken
        self.userSettings = userSettings
        self.publicId = publicId
        self.groupId = groupId
        self.type = type
        self.skill = skill
        self.icdCodes = icdCodes
        self.additionalInfoList = additionalInfoList
        self.userStatus = userStatus
        self.careTaker = careTaker
        self.alarmId = alarmId
        self.allergires = allergires
        self.room = room
        self.governmentId = governmentId
        self.internalId = internalId
        self.status = status
        self.age = age
        self.weight = weight
        self.pulse = pulse
        self.height = height
        self.hipSize = hipSize
        self.waistSize = waistSize
        self.category = category
        self.occupation = occupation
        self.education = education
        self.maratialstatus = maratialstatus
        self.parameters = parameters
        self.bloodGroup = bloodGroup
        self.profilePhotoId = profilePhotoId
        self.profilePhotoURL = profilePhotoURL
        self.emergencyContact = emergencyContact
        self.shiftId = shiftId
        self.shiftTimings = shiftTimings
        self.timeZone = timeZone
        self.hourlyPrice = hourlyPrice
        self.currency = currency
        self.profileTags = profileTags
        self.zipCode = zipCode
        self.encryptedPassword = encryptedPassword
        self.countryCode = countryCode
        self.insuranceInformation = insuranceInformation
        self.requestId = requestId
        self.partnerId = partnerId
        self.fullName = fullName
        self.address = address
        self.passwordResetEnabled = passwordResetEnabled
    }


}

