//
// CooeyAPIClient
// DeviceActivityPeriodSettings.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct DeviceActivityPeriodSettings: Codable {

    public var day: String?
    public var night: String?
    public var sleep: String?

    public init() {
    }

    public init(day: String?, night: String?, sleep: String?) {
        self.day = day
        self.night = night
        self.sleep = sleep
    }


}

