//
// CooeyAPIClient
// Device.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Device: Codable {

    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var id: String?
    public var userId: String?
    public var deviceId: String?
    public var name: String?
    public var type: String?
    public var parameters: String?
    public var mobileNumber: String?
    public var status: String?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, id: String?, userId: String?, deviceId: String?, name: String?, type: String?, parameters: String?, mobileNumber: String?, status: String?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.id = id
        self.userId = userId
        self.deviceId = deviceId
        self.name = name
        self.type = type
        self.parameters = parameters
        self.mobileNumber = mobileNumber
        self.status = status
    }


}

