//
// CooeyAPIClient
// DeviceSpecification.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct DeviceSpecification: Codable {

    public enum Capabilities: String, Codable { 
        case bloodPressure = "BLOOD_PRESSURE"
        case bloodGlucose = "BLOOD_GLUCOSE"
        case hemoglobin = "HEMOGLOBIN"
        case weight = "WEIGHT"
        case bodyAnalysis = "BODY_ANALYSIS"
        case spo2 = "SPO2"
        case ecg = "ECG"
        case heartRate = "HEART_RATE"
        case urineAnalysis = "URINE_ANALYSIS"
        case sleepTracking = "SLEEP_TRACKING"
        case bmi = "BMI"
        case fatPercentage = "FAT_PERCENTAGE"
        case waterContent = "WATER_CONTENT"
        case hba1c = "HBA1C"
        case lipidProfile = "LIPID_PROFILE"
        case boneMass = "BONE_MASS"
        case muscleMass = "MUSCLE_MASS"
        case temperature = "TEMPERATURE"
    }
    public var name: String?
    public var _description: String?
    public var brandName: String?
    public var brandUrl: String?
    public var capabilities: [Capabilities]?
    public var model: String?
    public var imageUrl: String?
    public var toBePaired: Bool?

    public init() {
    }

    public init(name: String?, _description: String?, brandName: String?, brandUrl: String?, capabilities: [Capabilities]?, model: String?, imageUrl: String?, toBePaired: Bool?) {
        self.name = name
        self._description = _description
        self.brandName = brandName
        self.brandUrl = brandUrl
        self.capabilities = capabilities
        self.model = model
        self.imageUrl = imageUrl
        self.toBePaired = toBePaired
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case brandName
        case brandUrl
        case capabilities
        case model
        case imageUrl
        case toBePaired
    }


}

