//
// CooeyAPIClient
// Device.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Device: Codable {

    public enum DeviceCapabilities: String, Codable { 
        case bloodPressure = "BLOOD_PRESSURE"
        case bloodGlucose = "BLOOD_GLUCOSE"
        case hemoglobin = "HEMOGLOBIN"
        case weight = "WEIGHT"
        case bodyAnalysis = "BODY_ANALYSIS"
        case spo2 = "SPO2"
        case ecg = "ECG"
        case heartRate = "HEART_RATE"
        case urineAnalysis = "URINE_ANALYSIS"
        case sleepTracking = "SLEEP_TRACKING"
        case bmi = "BMI"
        case fatPercentage = "FAT_PERCENTAGE"
        case waterContent = "WATER_CONTENT"
        case hba1c = "HBA1C"
        case lipidProfile = "LIPID_PROFILE"
        case boneMass = "BONE_MASS"
        case muscleMass = "MUSCLE_MASS"
        case temperature = "TEMPERATURE"
    }
    public var model: String?
    public var deviceCapabilities: [DeviceCapabilities]?

    public init() {
    }

    public init(model: String?, deviceCapabilities: [DeviceCapabilities]?) {
        self.model = model
        self.deviceCapabilities = deviceCapabilities
    }


}

