//
// CooeyAPIClient
// Engagement.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Engagement: Codable {

    public enum Channel: String, Codable { 
        case notification = "NOTIFICATION"
        case email = "EMAIL"
        case call = "CALL"
        case sms = "SMS"
        case voip = "VOIP"
    }
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var id: String?
    public var instruction: String?
    public var channel: Channel?
    public var schedule: Schedule?
    public var title: String?
    public var receiverId: String?
    public var ownerId: String?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, id: String?, instruction: String?, channel: Channel?, schedule: Schedule?, title: String?, receiverId: String?, ownerId: String?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.id = id
        self.instruction = instruction
        self.channel = channel
        self.schedule = schedule
        self.title = title
        self.receiverId = receiverId
        self.ownerId = ownerId
    }


}

