//
// CooeyAPIClient
// EpisodeAppointmentResponseDTO.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct EpisodeAppointmentResponseDTO: Codable {

    public enum OverallStatus: String, Codable { 
        case pending = "PENDING"
        case rejected = "REJECTED"
        case approved = "APPROVED"
        case deleted = "DELETED"
        case finished = "FINISHED"
        case all = "ALL"
    }
    public enum RequestedByAccountType: String, Codable { 
        case patient = "PATIENT"
        case tenant = "TENANT"
        case guardian = "GUARDIAN"
        case admin = "ADMIN"
        case careTaker = "CARE_TAKER"
        case user = "USER"
        case groupAdmin = "GROUP_ADMIN"
    }
    public enum ModelType: String, Codable { 
        case home = "HOME"
        case hospital = "HOSPITAL"
        case remote = "REMOTE"
        case referral = "REFERRAL"
    }
    public var appointmentId: String?
    public var title: String?
    public var _description: String?
    public var attenderName: String?
    public var attendeeName: String?
    public var serviceIds: [String]?
    public var schedule: Schedule?
    public var overallStatus: OverallStatus?
    public var attenderId: String?
    public var attendeeId: String?
    public var completedBy: String?
    public var completedOn: Int64?
    public var requestedByAccountType: RequestedByAccountType?
    public var chatSessionId: String?
    public var type: ModelType?
    public var parentId: String?
    public var active: Bool?
    public var archived: Bool?

    public init() {
    }

    public init(appointmentId: String?, title: String?, _description: String?, attenderName: String?, attendeeName: String?, serviceIds: [String]?, schedule: Schedule?, overallStatus: OverallStatus?, attenderId: String?, attendeeId: String?, completedBy: String?, completedOn: Int64?, requestedByAccountType: RequestedByAccountType?, chatSessionId: String?, type: ModelType?, parentId: String?, active: Bool?, archived: Bool?) {
        self.appointmentId = appointmentId
        self.title = title
        self._description = _description
        self.attenderName = attenderName
        self.attendeeName = attendeeName
        self.serviceIds = serviceIds
        self.schedule = schedule
        self.overallStatus = overallStatus
        self.attenderId = attenderId
        self.attendeeId = attendeeId
        self.completedBy = completedBy
        self.completedOn = completedOn
        self.requestedByAccountType = requestedByAccountType
        self.chatSessionId = chatSessionId
        self.type = type
        self.parentId = parentId
        self.active = active
        self.archived = archived
    }

    public enum CodingKeys: String, CodingKey { 
        case appointmentId
        case title
        case _description = "description"
        case attenderName
        case attendeeName
        case serviceIds
        case schedule
        case overallStatus
        case attenderId
        case attendeeId
        case completedBy
        case completedOn
        case requestedByAccountType
        case chatSessionId
        case type
        case parentId
        case active
        case archived
    }


}

