//
// CooeyAPIClient
// Episode.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Episode: Codable {

    public enum EpisodeType: String, Codable { 
        case rpm = "RPM"
        case homeAide = "HOME_AIDE"
        case general = "GENERAL"
    }
    public enum Status: String, Codable { 
        case completed = "COMPLETED"
        case suspended = "SUSPENDED"
        case paused = "PAUSED"
        case inProgress = "IN_PROGRESS"
        case pendingStart = "PENDING_START"
    }
    public var id: String?
    public var patientId: String?
    public var startTime: Int64?
    public var endTime: Int64?
    public var careplanId: String?
    public var episodeType: EpisodeType?
    public var properties: [String:String]?
    public var status: Status?
    public var icdCodeList: [Code]?
    public var cptCodeList: [Code]?
    public var consentFiles: [String]?
    public var deviceModels: [String]?
    public var insuranceInformation: EpisodeInsuranceInformation?
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var noteId: String?
    public var archived: Bool?
    public var active: Bool?

    public init() {
    }

    public init(id: String?, patientId: String?, startTime: Int64?, endTime: Int64?, careplanId: String?, episodeType: EpisodeType?, properties: [String:String]?, status: Status?, icdCodeList: [Code]?, cptCodeList: [Code]?, consentFiles: [String]?, deviceModels: [String]?, insuranceInformation: EpisodeInsuranceInformation?, createdOn: Int64?, updatedOn: Int64?, tenantId: String?, noteId: String?, archived: Bool?, active: Bool?) {
        self.id = id
        self.patientId = patientId
        self.startTime = startTime
        self.endTime = endTime
        self.careplanId = careplanId
        self.episodeType = episodeType
        self.properties = properties
        self.status = status
        self.icdCodeList = icdCodeList
        self.cptCodeList = cptCodeList
        self.consentFiles = consentFiles
        self.deviceModels = deviceModels
        self.insuranceInformation = insuranceInformation
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.noteId = noteId
        self.archived = archived
        self.active = active
    }


}

