//
// CooeyAPIClient
// EpisodeInsuranceInformation.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct EpisodeInsuranceInformation: Codable {

    public var primaryInsuranceDetails: Insurance?
    public var secondaryInsured: Bool?
    public var secondaryInsuranceDetails: Insurance?

    public init() {
    }

    public init(primaryInsuranceDetails: Insurance, secondaryInsured: Bool?, secondaryInsuranceDetails: Insurance?) {
        self.primaryInsuranceDetails = primaryInsuranceDetails
        self.secondaryInsured = secondaryInsured
        self.secondaryInsuranceDetails = secondaryInsuranceDetails
    }


}

