//
// CooeyAPIClient
// Event.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Event: Codable {

    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var id: String?
    public var name: String?
    public var start: Int64?
    public var end: Int64?
    public var enableNotification: Bool?
    public var notificationBefore: Int64?
    public var userId: String?
    public var ownerId: String?
    public var category: String?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, id: String?, name: String?, start: Int64?, end: Int64?, enableNotification: Bool?, notificationBefore: Int64?, userId: String?, ownerId: String?, category: String?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.id = id
        self.name = name
        self.start = start
        self.end = end
        self.enableNotification = enableNotification
        self.notificationBefore = notificationBefore
        self.userId = userId
        self.ownerId = ownerId
        self.category = category
    }


}

