//
// CooeyAPIClient
// ExcelConfig.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ExcelConfig: Codable {

    public var id: Int?
    public var className: String?
    public var collectionName: String?
    public var propertyMapperList: [PropertyMapper]?
    public var pakage: String?

    public init() {
    }

    public init(id: Int?, className: String?, collectionName: String?, propertyMapperList: [PropertyMapper]?, pakage: String?) {
        self.id = id
        self.className = className
        self.collectionName = collectionName
        self.propertyMapperList = propertyMapperList
        self.pakage = pakage
    }


}

