//
// CooeyAPIClient
// FieldComponent.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct FieldComponent: Codable {

    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var title: String?
    public var type: String?
    public var contextGraphEnabled: Bool?
    public var template: JSONValue?
    public var mandatory: Bool?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, title: String?, type: String?, contextGraphEnabled: Bool?, template: JSONValue?, mandatory: Bool?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.title = title
        self.type = type
        self.contextGraphEnabled = contextGraphEnabled
        self.template = template
        self.mandatory = mandatory
    }


}

