//
// CooeyAPIClient
// FollowUpResponse.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct FollowUpResponse: Codable {

    public var id: String?
    public var tasks: [FollowUpTask]?
    public var leadName: String?
    public var leadId: String?
    public var scheduledOn: Int64?
    public var createdOn: Int64?

    public init() {
    }

    public init(id: String?, tasks: [FollowUpTask]?, leadName: String?, leadId: String?, scheduledOn: Int64?, createdOn: Int64?) {
        self.id = id
        self.tasks = tasks
        self.leadName = leadName
        self.leadId = leadId
        self.scheduledOn = scheduledOn
        self.createdOn = createdOn
    }


}

