//
// CooeyAPIClient
// Food.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Food: Codable {

    public var id: String?
    public var calories: String?
    public var carbs: String?
    public var fat: String?
    public var name: String?
    public var proteins: String?
    public var servingSize: String?
    public var type: String?

    public init() {
    }

    public init(id: String?, calories: String?, carbs: String?, fat: String?, name: String?, proteins: String?, servingSize: String?, type: String?) {
        self.id = id
        self.calories = calories
        self.carbs = carbs
        self.fat = fat
        self.name = name
        self.proteins = proteins
        self.servingSize = servingSize
        self.type = type
    }


}

