//
// CooeyAPIClient
// FormSection.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct FormSection: Codable {

    public enum SectionMode: String, Codable { 
        case cascading = "CASCADING"
        case regular = "REGULAR"
    }
    public var sectionHeading: String?
    public var sectionDescription: String?
    public var fieldInputs: FieldInputs?
    public var sectionMode: SectionMode?
    public var formId: String?

    public init() {
    }

    public init(sectionHeading: String?, sectionDescription: String?, fieldInputs: FieldInputs?, sectionMode: SectionMode?, formId: String?) {
        self.sectionHeading = sectionHeading
        self.sectionDescription = sectionDescription
        self.fieldInputs = fieldInputs
        self.sectionMode = sectionMode
        self.formId = formId
    }


}

