//
// CooeyAPIClient
// FormBluePrint.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct FormBluePrint: Codable {

    public enum OwnerType: String, Codable { 
        case tenant = "TENANT"
        case admin = "ADMIN"
        case careTaker = "CARE_TAKER"
        case patient = "PATIENT"
        case guardian = "GUARDIAN"
        case global = "GLOBAL"
    }
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var ownerType: OwnerType?
    public var ownerId: String?
    public var formHeader: FormHeader?
    public var formFooter: FormFooter?
    public var percentageComplete: Double?
    public var id: String?
    public var name: String?
    public var sectionList: [FormSection]?
    public var type: String?
    public var tags: [String]?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, ownerType: OwnerType?, ownerId: String?, formHeader: FormHeader?, formFooter: FormFooter?, percentageComplete: Double?, id: String?, name: String?, sectionList: [FormSection]?, type: String?, tags: [String]?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.ownerType = ownerType
        self.ownerId = ownerId
        self.formHeader = formHeader
        self.formFooter = formFooter
        self.percentageComplete = percentageComplete
        self.id = id
        self.name = name
        self.sectionList = sectionList
        self.type = type
        self.tags = tags
    }


}

