//
// CooeyAPIClient
// GrouppedActionResponse.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct GrouppedActionResponse: Codable {

    public var name: String?
    public var id: String?
    public var actionItems: [ActionItem]?

    public init() {
    }

    public init(name: String?, id: String?, actionItems: [ActionItem]?) {
        self.name = name
        self.id = id
        self.actionItems = actionItems
    }


}

