//
// CooeyAPIClient
// Groups.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Groups: Codable {

    public var name: String?
    public var subGroups: String?

    public init() {
    }

    public init(name: String?, subGroups: String?) {
        self.name = name
        self.subGroups = subGroups
    }


}

