//
// CooeyAPIClient
// Guardian.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Guardian: Codable {

    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var id: String?
    public var userId: String?
    public var guardianId: String?
    public var name: String?
    public var contacts: [Contact]?
    public var relationship: String?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, id: String?, userId: String?, guardianId: String?, name: String?, contacts: [Contact]?, relationship: String?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.id = id
        self.userId = userId
        self.guardianId = guardianId
        self.name = name
        self.contacts = contacts
        self.relationship = relationship
    }


}

