//
// CooeyAPIClient
// HealthScoreConfig.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct HealthScoreConfig: Codable {

    public enum HealthScore: String, Codable { 
        case rothmanIndex = "ROTHMAN_INDEX"
        case cooey = "COOEY"
    }
    public var healthScore: HealthScore?
    public var parameters: [String:String]?
    public var enabled: Bool?

    public init() {
    }

    public init(healthScore: HealthScore?, parameters: [String:String]?, enabled: Bool?) {
        self.healthScore = healthScore
        self.parameters = parameters
        self.enabled = enabled
    }


}

