//
// CooeyAPIClient
// HipSize.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct HipSize: Codable {

    public var value: Float?
    public var unit: String?

    public init() {
    }

    public init(value: Float?, unit: String?) {
        self.value = value
        self.unit = unit
    }


}

