//
// CooeyAPIClient
// LeadRequest.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct LeadRequest: Codable {

    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var archived: Bool?
    public var tenantId: String?
    public var createdBy: String?
    public var assignedTo: String?
    public var source: String?
    public var domain: String?
    public var query: String?
    public var referredBy: String?
    public var referredTo: String?
    public var referralReason: String?
    public var insuranceCarrier: String?
    public var personInfo: PatientInfo?
    public var patientInfo: PatientInfo?
    public var leadSameAsPatient: Bool?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, archived: Bool?, tenantId: String?, createdBy: String?, assignedTo: String?, source: String?, domain: String?, query: String?, referredBy: String?, referredTo: String?, referralReason: String?, insuranceCarrier: String?, personInfo: PatientInfo?, patientInfo: PatientInfo?, leadSameAsPatient: Bool?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.archived = archived
        self.tenantId = tenantId
        self.createdBy = createdBy
        self.assignedTo = assignedTo
        self.source = source
        self.domain = domain
        self.query = query
        self.referredBy = referredBy
        self.referredTo = referredTo
        self.referralReason = referralReason
        self.insuranceCarrier = insuranceCarrier
        self.personInfo = personInfo
        self.patientInfo = patientInfo
        self.leadSameAsPatient = leadSameAsPatient
    }


}

