//
// CooeyAPIClient
// Meal.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Meal: Codable {

    public var name: String?
    public var dietId: String?
    public var tagId: String?
    public var calories: String?
    public var startTime: String?
    public var endTime: String?
    public var mealPlans: [MealPlan]?
    public var carbs: String?
    public var fiber: String?
    public var dietRecomendation: String?

    public init() {
    }

    public init(name: String?, dietId: String?, tagId: String?, calories: String?, startTime: String?, endTime: String?, mealPlans: [MealPlan]?, carbs: String?, fiber: String?, dietRecomendation: String?) {
        self.name = name
        self.dietId = dietId
        self.tagId = tagId
        self.calories = calories
        self.startTime = startTime
        self.endTime = endTime
        self.mealPlans = mealPlans
        self.carbs = carbs
        self.fiber = fiber
        self.dietRecomendation = dietRecomendation
    }


}

