//
// CooeyAPIClient
// ModelResponse.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ModelResponse: Codable {

    public var entity: String?
    public var cookies: [String:NewCookie]?
    public var lastModified: Date?
    public var date: Date?
    public var headers: [String:[String]]?
    public var status: Int?
    public var mediaType: MediaType?
    public var metadata: [String:[String]]?
    public var allowedMethods: [String]?
    public var statusInfo: StatusType?
    public var entityTag: EntityTag?
    public var links: [Link]?
    public var stringHeaders: [String:[String]]?
    public var length: Int?
    public var language: Locale?
    public var location: String?

    public init() {
    }

    public init(entity: String?, cookies: [String:NewCookie]?, lastModified: Date?, date: Date?, headers: [String:[String]]?, status: Int?, mediaType: MediaType?, metadata: [String:[String]]?, allowedMethods: [String]?, statusInfo: StatusType?, entityTag: EntityTag?, links: [Link]?, stringHeaders: [String:[String]]?, length: Int?, language: Locale?, location: String?) {
        self.entity = entity
        self.cookies = cookies
        self.lastModified = lastModified
        self.date = date
        self.headers = headers
        self.status = status
        self.mediaType = mediaType
        self.metadata = metadata
        self.allowedMethods = allowedMethods
        self.statusInfo = statusInfo
        self.entityTag = entityTag
        self.links = links
        self.stringHeaders = stringHeaders
        self.length = length
        self.language = language
        self.location = location
    }


}

