//
// CooeyAPIClient
// OnboardSettings.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct OnboardSettings: Codable {

    public enum CommunicationMode: String, Codable { 
        case email = "EMAIL"
        case customEmail = "CUSTOM_EMAIL"
        case phone = "PHONE"
        case _none = "NONE"
    }
    public var communicationMode: CommunicationMode?
    public var communicationSettings: [String:String]?

    public init() {
    }

    public init(communicationMode: CommunicationMode?, communicationSettings: [String:String]?) {
        self.communicationMode = communicationMode
        self.communicationSettings = communicationSettings
    }


}

