//
// CooeyAPIClient
// PagedResultAppointment.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct PagedResultAppointment: Codable {

    public var totalCount: Int64?
    public var offset: Int64?
    public var result: [Appointment]?

    public init() {
    }

    public init(totalCount: Int64?, offset: Int64?, result: [Appointment]?) {
        self.totalCount = totalCount
        self.offset = offset
        self.result = result
    }


}

