//
// CooeyAPIClient
// PatchRequest.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct PatchRequest: Codable {

    public var op: String?
    public var path: String?
    public var value: String?

    public init() {
    }

    public init(op: String?, path: String?, value: String?) {
        self.op = op
        self.path = path
        self.value = value
    }


}

