//
// CooeyAPIClient
// PatientCommunicationResponseDTO.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct PatientCommunicationResponseDTO: Codable {

    public enum Mode: String, Codable { 
        case call = "CALL"
        case videoCall = "VIDEO_CALL"
    }
    public var id: String?
    public var episodeId: String?
    public var caretakerId: String?
    public var patientId: String?
    public var date: Int64?
    public var startTime: Int64?
    public var endTime: Int64?
    public var duration: String?
    public var notes: String?
    public var mode: Mode?
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var archived: Bool?
    public var active: Bool?
    public var patientName: String?
    public var caretakerName: String?
    public var durationInMilliSeconds: Int64?

    public init() {
    }

    public init(id: String?, episodeId: String?, caretakerId: String?, patientId: String?, date: Int64?, startTime: Int64?, endTime: Int64?, duration: String?, notes: String?, mode: Mode?, createdOn: Int64?, updatedOn: Int64?, tenantId: String?, archived: Bool?, active: Bool?, patientName: String?, caretakerName: String?, durationInMilliSeconds: Int64?) {
        self.id = id
        self.episodeId = episodeId
        self.caretakerId = caretakerId
        self.patientId = patientId
        self.date = date
        self.startTime = startTime
        self.endTime = endTime
        self.duration = duration
        self.notes = notes
        self.mode = mode
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.archived = archived
        self.active = active
        self.patientName = patientName
        self.caretakerName = caretakerName
        self.durationInMilliSeconds = durationInMilliSeconds
    }


}

