//
// CooeyAPIClient
// PatientInfo.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct PatientInfo: Codable {

    public var firstName: String?
    public var middleName: String?
    public var lastName: String?
    public var email: String?
    public var phoneNumber: String?

    public init() {
    }

    public init(firstName: String, middleName: String?, lastName: String?, email: String, phoneNumber: String) {
        self.firstName = firstName
        self.middleName = middleName
        self.lastName = lastName
        self.email = email
        self.phoneNumber = phoneNumber
    }


}

