//
// CooeyAPIClient
// PatientVitalStatsResponse.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct PatientVitalStatsResponse: Codable {

    public var vitalCount: Int?
    public var vitalType: String?
    public var name: String?
    public var vitalLimitCrossedCount: Int?
    public var lastMesaured: Vital?

    public init() {
    }

    public init(vitalCount: Int?, vitalType: String?, name: String?, vitalLimitCrossedCount: Int?, lastMesaured: Vital?) {
        self.vitalCount = vitalCount
        self.vitalType = vitalType
        self.name = name
        self.vitalLimitCrossedCount = vitalLimitCrossedCount
        self.lastMesaured = lastMesaured
    }


}

