//
// CooeyAPIClient
// Patient.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Patient: Codable {

    public var orgId: Int64?
    public var facId: Int64?
    public var patientId: Int64?
    public var medicalRecordNumber: String?
    public var patientExternalId: String?
    public var patientStatus: String?
    public var bedId: Int64?
    public var bedDesc: String?
    public var roomDesc: String?
    public var floorDesc: String?
    public var unitDesc: String?
    public var unitId: Int64?
    public var lastName: String?
    public var firstName: String?
    public var middleName: String?
    public var outpatient: Bool?
    public var birthDate: String?
    public var admissionDate: String?
    public var waitingList: Bool?
    public var hasPhoto: Bool?
    public var gender: String?
    public var ethnicityDesc: String?
    public var languageCode: String?
    public var languageDesc: String?
    public var smokingStatusCode: String?
    public var smokingStatusDesc: String?
    public var religion: String?
    public var citizenship: String?
    public var maritalStatus: String?
    public var previousAddress: PreviousAddress?
    public var homePhone: String?
    public var email: String?
    public var patientRaces: [PatientRace]?
    public var patientContacts: [PatientContact]?
    public var dischargeDate: String?

    public init() {
    }

    public init(orgId: Int64?, facId: Int64?, patientId: Int64?, medicalRecordNumber: String?, patientExternalId: String?, patientStatus: String?, bedId: Int64?, bedDesc: String?, roomDesc: String?, floorDesc: String?, unitDesc: String?, unitId: Int64?, lastName: String?, firstName: String?, middleName: String?, outpatient: Bool?, birthDate: String?, admissionDate: String?, waitingList: Bool?, hasPhoto: Bool?, gender: String?, ethnicityDesc: String?, languageCode: String?, languageDesc: String?, smokingStatusCode: String?, smokingStatusDesc: String?, religion: String?, citizenship: String?, maritalStatus: String?, previousAddress: PreviousAddress?, homePhone: String?, email: String?, patientRaces: [PatientRace]?, patientContacts: [PatientContact]?, dischargeDate: String?) {
        self.orgId = orgId
        self.facId = facId
        self.patientId = patientId
        self.medicalRecordNumber = medicalRecordNumber
        self.patientExternalId = patientExternalId
        self.patientStatus = patientStatus
        self.bedId = bedId
        self.bedDesc = bedDesc
        self.roomDesc = roomDesc
        self.floorDesc = floorDesc
        self.unitDesc = unitDesc
        self.unitId = unitId
        self.lastName = lastName
        self.firstName = firstName
        self.middleName = middleName
        self.outpatient = outpatient
        self.birthDate = birthDate
        self.admissionDate = admissionDate
        self.waitingList = waitingList
        self.hasPhoto = hasPhoto
        self.gender = gender
        self.ethnicityDesc = ethnicityDesc
        self.languageCode = languageCode
        self.languageDesc = languageDesc
        self.smokingStatusCode = smokingStatusCode
        self.smokingStatusDesc = smokingStatusDesc
        self.religion = religion
        self.citizenship = citizenship
        self.maritalStatus = maritalStatus
        self.previousAddress = previousAddress
        self.homePhone = homePhone
        self.email = email
        self.patientRaces = patientRaces
        self.patientContacts = patientContacts
        self.dischargeDate = dischargeDate
    }


}

