//
// CooeyAPIClient
// PatientRace.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct PatientRace: Codable {

    public var raceDesc: String?

    public init() {
    }

    public init(raceDesc: String?) {
        self.raceDesc = raceDesc
    }


}

