//
// CooeyAPIClient
// ReferralSettings.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ReferralSettings: Codable {

    public var prelimFormBluePrints: [String]?
    public var evaluationFormBluePrints: [String]?

    public init() {
    }

    public init(prelimFormBluePrints: [String]?, evaluationFormBluePrints: [String]?) {
        self.prelimFormBluePrints = prelimFormBluePrints
        self.evaluationFormBluePrints = evaluationFormBluePrints
    }


}

