//
// CooeyAPIClient
// Repeat.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Repeat: Codable {

    public enum ModelType: String, Codable { 
        case daily = "DAILY"
        case weekly = "WEEKLY"
        case monthly = "MONTHLY"
        case yearly = "YEARLY"
    }
    public enum OccuranceType: String, Codable { 
        case noOfDays = "NO_OF_DAYS"
        case onDate = "ON_DATE"
    }
    public var type: ModelType?
    public var frequency: Int?
    public var repeatOn: DaysActivationState?
    public var startDate: Int64?
    public var occuranceType: OccuranceType?
    public var occurances: String?
    public var summary: String?

    public init() {
    }

    public init(type: ModelType?, frequency: Int?, repeatOn: DaysActivationState?, startDate: Int64?, occuranceType: OccuranceType?, occurances: String?, summary: String?) {
        self.type = type
        self.frequency = frequency
        self.repeatOn = repeatOn
        self.startDate = startDate
        self.occuranceType = occuranceType
        self.occurances = occurances
        self.summary = summary
    }


}

