//
// CooeyAPIClient
// ReportRequest.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ReportRequest: Codable {

    public enum Status: String, Codable { 
        case pending = "PENDING"
        case done = "DONE"
        case cancelled = "CANCELLED"
    }
    public enum ReportContext: String, Codable { 
        case rpm = "RPM"
        case patientSummary = "PATIENT_SUMMARY"
        case printableVital = "PRINTABLE_VITAL"
        case printablePrescription = "PRINTABLE_PRESCRIPTION"
    }
    public var id: String?
    public var requestId: String?
    public var fileName: String?
    public var userId: String?
    public var tenantId: String?
    public var status: Status?
    public var reportContext: ReportContext?
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var reportFormat: String?

    public init() {
    }

    public init(id: String?, requestId: String?, fileName: String?, userId: String?, tenantId: String?, status: Status?, reportContext: ReportContext?, createdOn: Int64?, updatedOn: Int64?, reportFormat: String?) {
        self.id = id
        self.requestId = requestId
        self.fileName = fileName
        self.userId = userId
        self.tenantId = tenantId
        self.status = status
        self.reportContext = reportContext
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.reportFormat = reportFormat
    }


}

