//
// CooeyAPIClient
// ScoreParametersSection.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ScoreParametersSection: Codable {

    public var sectionName: String?
    public var scoreParameters: [ScoreParameter]?

    public init() {
    }

    public init(sectionName: String?, scoreParameters: [ScoreParameter]?) {
        self.sectionName = sectionName
        self.scoreParameters = scoreParameters
    }


}

