//
// CooeyAPIClient
// ScoreCalculation.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ScoreCalculation: Codable {

    public var score: Int?
    public var calculatedOn: Int64?
    public var scoreParametersSections: [ScoreParametersSection]?

    public init() {
    }

    public init(score: Int?, calculatedOn: Int64?, scoreParametersSections: [ScoreParametersSection]?) {
        self.score = score
        self.calculatedOn = calculatedOn
        self.scoreParametersSections = scoreParametersSections
    }


}

