//
// CooeyAPIClient
// ServiceForm.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct ServiceForm: Codable {

    public var name: String?
    public var url: String?
    public var type: String?

    public init() {
    }

    public init(name: String?, url: String?, type: String?) {
        self.name = name
        self.url = url
        self.type = type
    }


}

