//
// CooeyAPIClient
// StatsRepsonse.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct StatsRepsonse: Codable {

    public var alertMap: [String:[Alert]]?
    public var careplanMap: [String:[Careplan]]?
    public var cartakerPatientMap: [String:[User]]?
    public var taskStatusMap: [String:TaskStatus]?

    public init() {
    }

    public init(alertMap: [String:[Alert]]?, careplanMap: [String:[Careplan]]?, cartakerPatientMap: [String:[User]]?, taskStatusMap: [String:TaskStatus]?) {
        self.alertMap = alertMap
        self.careplanMap = careplanMap
        self.cartakerPatientMap = cartakerPatientMap
        self.taskStatusMap = taskStatusMap
    }


}

