//
// CooeyAPIClient
// TemplateConfig.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct TemplateConfig: Codable {

    public var dietFeatureEnabled: Bool?
    public var contentFeatureEnabled: Bool?

    public init() {
    }

    public init(dietFeatureEnabled: Bool?, contentFeatureEnabled: Bool?) {
        self.dietFeatureEnabled = dietFeatureEnabled
        self.contentFeatureEnabled = contentFeatureEnabled
    }


}

