//
// CooeyAPIClient
// UnidentifiedValue.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct UnidentifiedValue: Codable {

    public var value: String?
    public var boundingBox: BoundingBox?

    public init() {
    }

    public init(value: String?, boundingBox: BoundingBox?) {
        self.value = value
        self.boundingBox = boundingBox
    }


}

