//
// CooeyAPIClient
// Units.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Units: Codable {

    public var heartRate: String?
    public var bloodSugar: String?
    public var bloodPressure: String?
    public var weight: String?
    public var height: String?
    public var temperature: String?
    public var respirations: String?
    public var oxygenSaturation: String?

    public init() {
    }

    public init(heartRate: String?, bloodSugar: String?, bloodPressure: String?, weight: String?, height: String?, temperature: String?, respirations: String?, oxygenSaturation: String?) {
        self.heartRate = heartRate
        self.bloodSugar = bloodSugar
        self.bloodPressure = bloodPressure
        self.weight = weight
        self.height = height
        self.temperature = temperature
        self.respirations = respirations
        self.oxygenSaturation = oxygenSaturation
    }


}

