//
// CooeyAPIClient
// UserHealthScore.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct UserHealthScore: Codable {

    public var id: String?
    public var patientId: String?
    public var healthScore: HealthScore?
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var archived: Bool?
    public var active: Bool?

    public init() {
    }

    public init(id: String?, patientId: String?, healthScore: HealthScore?, createdOn: Int64?, updatedOn: Int64?, archived: Bool?, active: Bool?) {
        self.id = id
        self.patientId = patientId
        self.healthScore = healthScore
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.archived = archived
        self.active = active
    }


}

