//
// CooeyAPIClient
// UserCertificate.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct UserCertificate: Codable {

    public enum UserType: String, Codable { 
        case tenant = "TENANT"
        case admin = "ADMIN"
        case careTaker = "CARE_TAKER"
        case patient = "PATIENT"
        case guardian = "GUARDIAN"
        case global = "GLOBAL"
    }
    public enum State: String, Codable { 
        case active = "ACTIVE"
        case expired = "EXPIRED"
        case abandoned = "ABANDONED"
        case pending = "PENDING"
    }
    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var id: String?
    public var userId: String?
    public var userType: UserType?
    public var certificateURL: String?
    public var validTill: Int64?
    public var effectiveFrom: Int64?
    public var state: State?
    public var certificateType: String?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, id: String?, userId: String?, userType: UserType?, certificateURL: String?, validTill: Int64?, effectiveFrom: Int64?, state: State?, certificateType: String?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.id = id
        self.userId = userId
        self.userType = userType
        self.certificateURL = certificateURL
        self.validTill = validTill
        self.effectiveFrom = effectiveFrom
        self.state = state
        self.certificateType = certificateType
    }


}

