//
// CooeyAPIClient
// UserInfo.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct UserInfo: Codable {

    public var createdOn: Int64?
    public var updatedOn: Int64?
    public var tenantId: String?
    public var applicationId: String?
    public var archived: Bool?
    public var externalId: String?
    public var active: Bool?
    public var cooeyId: String?
    public var orgId: Int64?
    public var username: String?
    public var name: String?
    public var title: String?
    public var defaultFacId: Int64?
    public var enabled: Bool?
    public var userId: Int64?
    public var passwordExpired: Bool?
    public var privilegeScopes: [String]?

    public init() {
    }

    public init(createdOn: Int64?, updatedOn: Int64?, tenantId: String?, applicationId: String?, archived: Bool?, externalId: String?, active: Bool?, cooeyId: String?, orgId: Int64?, username: String?, name: String?, title: String?, defaultFacId: Int64?, enabled: Bool?, userId: Int64?, passwordExpired: Bool?, privilegeScopes: [String]?) {
        self.createdOn = createdOn
        self.updatedOn = updatedOn
        self.tenantId = tenantId
        self.applicationId = applicationId
        self.archived = archived
        self.externalId = externalId
        self.active = active
        self.cooeyId = cooeyId
        self.orgId = orgId
        self.username = username
        self.name = name
        self.title = title
        self.defaultFacId = defaultFacId
        self.enabled = enabled
        self.userId = userId
        self.passwordExpired = passwordExpired
        self.privilegeScopes = privilegeScopes
    }


}

