//
// CooeyAPIClient
// VideoCallParticipationEvent.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct VideoCallParticipationEvent: Codable {

    public enum Event: String, Codable { 
        case joined = "CALL_JOINED"
        case rejected = "CALL_REJECTED"
        case exited = "CALL_EXITED"
    }
    public var id: String?
    public var sessionId: String?
    public var userId: String?
    public var event: Event?
    public var createdOn: Int64?

    public init() {
    }

    public init(id: String?, sessionId: String?, userId: String?, event: Event?, createdOn: Int64?) {
        self.id = id
        self.sessionId = sessionId
        self.userId = userId
        self.event = event
        self.createdOn = createdOn
    }


}

