//
// CooeyAPIClient
// Vitals.swift
//
// Generated by Eldhose Lomy
// https://github.com/eldhoselomy/swagger-codegen
//

import Foundation



public struct Vitals: Codable {

    public var name: String?
    public var primaryVitals: String?
    public var secondaryVitals: String?
    public var parameters: String?

    public init() {
    }

    public init(name: String?, primaryVitals: String?, secondaryVitals: String?, parameters: String?) {
        self.name = name
        self.primaryVitals = primaryVitals
        self.secondaryVitals = secondaryVitals
        self.parameters = parameters
    }


}

